### PR TITLE
Added a candidate package.json

### PR DESCRIPTION
**Pull request by jared-stilwell**
Based on our chat recently, it is obvious that you want to skip the spinning rims on the build system and keep things simple, and I agree :)

This commit includes a simple package.json which  allows you to push the project to npm so others can easily include it. It doesn't handle asset building at all, since it is generally up to the consumer of front-end modules to sort out their packaging and minification needs.

### CODE REVIEW

**Comment by tholman** [comment]
Was great to meet you the other day, this is perfect man!

Going to check it out this week, and get it in :o

**Comment by jared-stilwell** [comment]
@tholman likewise. I really dig this project. Thinking about how to approach package management for this with as little complication as possible is an interesting exercise. :) keep me posted with what you find.

**Comment by tholman** [comment]
Merging this in now, going to try to do the whole package npm deploy-y thing next!

**Comment by tholman** [comment]
Got there! - https://www.npmjs.com/package/@tholman/intense-images

It turns out it had to be scoped, because someone had used the name (I'm pretty sure I said anyone can publish, when I was trying to avoid the npm thing!)

But this is a big first step for me 💃

**Comment by jared-stilwell** [comment]
Nice! 👍

**Pull request merged**
