### PR TITLE
Dbl click bug fix (& loading class for image block), IE9 support (2d tra...

### PR DESCRIPTION
**Pull request by vedmant**
Hi, there! 

I've found some bugs and fixed them.

1. If you click twice while image is loading it will cause two figure blocks appearing. I've added "loading" class to image block, it can be also used for adding loading spinner.

2.  IE9 doesn't support 3d transitions, I've added test for 3d transitions and in case browser doesn't support it it will use 2d transitions instead. There is another story with mouse cursors, but my solution uses separate css file and I didn't add it for pull request.

PS: I'm novice with Forks & Pull Request, if I've done it wrong please tell me.

### CODE REVIEW

**Comment by tholman** [comment]
Sorry for dropping the ball so much on this one. The double click was fixed with - https://github.com/tholman/intense-images/pull/34

You're spot on about the ie9 thing, I might just use 2d transforms for all of them, and forget about 3d all together!

**Comment by vedmant** [comment]
I don't think using only 2d transform is good idea, it works much slower compared to 3d.

**Comment by tholman** [comment]
Feels good to me. Added backface visibility hidden, to keep hardware compositing too. Its not like we're transforming 1000 images at once either ;)

**Comment by vedmant** [comment]
When I tried only 2d it worked not so smooth, mayte your hardware is more powerful. I selected your plugin exactly because it worked smoother than others.

**Comment by tholman** [comment]
There is no reason why backface visibility combined with 2d transform would be any slower.

**Comment by vedmant** [comment]
That's just what I experienced when was fixing IE9 problem, that's why I've added test for 3d.

**Pull request closed without merging**
